# This is a basic workflow to help you get started with Actions

name: pacman-check

# Controls when the action will run. 
on:
#  schedule:
#    - cron: '*/60 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build
        run: |
          sudo apt-get update
          git clone https://github.com/ThePoorPilot/pacman-utils.git
          cp ./pacman-utils/auto/token.txt ./
          cp ./pacman-utils/auto/push.sh ./
          sed -i 's/insert_token_here/'"${{ secrets.SECRET_TOKEN }}"'/g' ./token.txt
          cd ./pacman-utils/auto
          ./auto.sh
          cd ../
          echo "FILES_EXIST=$(ls -1 *.deb 2>/dev/null | wc -l)" >> $GITHUB_ENV
          cd ../
          rm ./push.sh
          rm ./token.txt
      - name: Push
        if: ${{ env.FILES_EXIST > '0' }}
        run: |
          cd ./pacman-utils
          rm ./*.deb
          echo "Pushing revised auto.sh to GitHub..."
          git config --global user.name "ThePoorPilot"
          git config --global user.email "ios8jailbreakpangu@gmail.com"
          git add .
          git commit -m 'changed version number in build checking'
          git push https://ThePoorPilot:"${{ secrets.SECRET_TOKEN }}"@github.com/ThePoorPilot/pacman-utils.git 
